let CURRENT_LANG = 'en';

function t(text) {
  return (CURRENT_LANG === 'en' && LANG_DICT[text]) ? LANG_DICT[text] : text;
}

const LANG_DICT = {
  "三水区": "Sanshui District",
  "三水南站": "Sanshui South Station",
  "三水站": "Sanshui Station",
  "东区": "East District",
  "东升站": "Dongsheng Station",
  "东莞东站": "Dongguan East Station",
  "东莞市": "Dongguan City",
  "东莞站": "Dongguan Station",
  "中山北站": "Zhongshan North Station",
  "中山市": "Zhongshan City",
  "中山站": "Zhongshan Station",
  "中西区": "Central and Western District",
  "九龙城区": "Kowloon City District",
  "从化区": "Conghua District",
  "佛山站": "Foshan Station",
  "元朗区": "Yuen Long District",
  "光明区": "Guangming District",
  "光明城站": "Guangmingcheng Station",
  "前山站": "Qianshan Station",
  "北区": "North District",
  "北滘站": "Beijiao Station",
  "南区": "Southern District",
  "南头站": "Nantou Station",
  "南山区": "Nanshan District",
  "南朗站": "Nanlang Station",
  "南沙区": "Nansha District",
  "南海区": "Nanhai District",
  "博罗县": "Boluo County",
  "古镇站": "Guzhen Station",
  "台山市": "Taishan City",
  "唐家湾站": "Tangjiawan Station",
  "四会市": "Sihui City",
  "坪山区": "Pingshan District",
  "增城区": "Zengcheng District",
  "大埔区": "Tai Po District",
  "天河区": "Tianhe District",
  "宝安区": "Bao'an District",
  "容桂站": "Ronggui Station",
  "封开县": "Fengkai County",
  "小榄站": "Xiaolan Station",
  "屯门区": "Tuen Mun District",
  "常平站": "Changping Station",
  "广宁县": "Guangning County",
  "广宁站": "Guangning Station",
  "广州东站": "Guangzhou East Station",
  "广州北站": "Guangzhou North Station",
  "广州南站": "Guangzhou South Station",
  "广州站": "Guangzhou Station",
  "庆盛站": "Qingsheng Station",
  "开平市": "Kaiping City",
  "德庆县": "Deqing County",
  "怀集县": "Huaiji County",
  "怀集站": "Huaiji Station",
  "恩平市": "Enping City",
  "惠东县": "Huidong County",
  "惠东站": "Huidong Station",
  "惠城区": "Huicheng District",
  "惠州南站": "Huizhou South Station",
  "惠州站": "Huizhou Station",
  "惠州西站": "Huizhou West Station",
  "惠阳区": "Huiyang District",
  "斗门区": "Doumen District",
  "新会区": "Xinhui District",
  "新会站": "Xinhui Station",
  "明珠站": "Mingzhu Station",
  "樟木头站": "Zhangmutou Station",
  "江海区": "Jianghai District",
  "江门站": "Jiangmen Station",
  "沙田区": "Sha Tin District",
  "油尖旺区": "Yau Tsim Mong District",
  "海珠区": "Haizhu District",
  "深圳东站": "Shenzhen East Station",
  "深圳北站": "Shenzhen North Station",
  "深圳坪山站": "Shenzhen Pingshan Station",
  "深圳站": "Shenzhen Station",
  "深圳西站": "Shenzhen West Station",
  "深水埗区": "Sham Shui Po District",
  "湾仔区": "Wan Chai District",
  "澳门特别行政区": "Macau Special Administrative Region",
  "珠海北站": "Zhuhai North Station",
  "珠海站": "Zhuhai Station",
  "番禺区": "Panyu District",
  "白云区": "Baiyun District",
  "盐田区": "Yantian District",
  "碧江站": "Bijiang Station",
  "禅城区": "Chancheng District",
  "福田区": "Futian District",
  "离岛区": "Islands District",
  "端州区": "Duanzhou District",
  "罗湖区": "Luohu District",
  "肇庆东站": "Zhaoqing East Station",
  "肇庆站": "Zhaoqing Station",
  "花都区": "Huadu District",
  "荃湾区": "Tsuen Wan District",
  "荔湾区": "Liwan District",
  "葵青区": "Kwai Tsing District",
  "蓬江区": "Pengjiang District",
  "虎门站": "Humen Station",
  "西九龙站": "West Kowloon Station",
  "西贡区": "Sai Kung District",
  "观塘区": "Kwun Tong District",
  "越秀区": "Yuexiu District",
  "金湾区": "Jinwan District",
  "顺德区": "Shunde District",
  "顺德学院站": "Shunde College Station",
  "顺德站": "Shunde Station",
  "香洲区": "Xiangzhou District",
  "高明区": "Gaoming District",
  "高要区": "Gaoyao District",
  "鹤山市": "Heshan City",
  "黄埔区": "Huangpu District",
  "黄大仙区": "Wong Tai Sin District",
  "鼎湖区": "Dinghu District",
  "龙华区": "Longhua District",
  "龙岗区": "Longgang District",
  "龙门县": "Longmen County",
};
